################################### Default Configuration ############################
baseurl = "https://icy-ground-07f0ffa10-1.centralus.azurestaticapps.net/"
title = "Acrily-K"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here
defaultContentLanguage = "es"


# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
# [[params.plugins.css]]
# link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Contacto"
url = "contact"
weight = 5

# footer menu
[[menu.footer]]
name = "Contacto"
url = "contact"
weight = 2

[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3

[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4


########################### Default parameters ##########################
[params]
logo = "images/acryli-k-logo.png"
logo_width = "100px"
# Meta data
description = "Ideas en Acrílico"
author = "Thomas"
# currency
currency = "$"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# snipcart public api key
snipcart_api = ""

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours


################################### English language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-ms"
contentDir = "content/spanish"
weight = 1
# copyright
copyright = "Designed by Thomas von Mentlen"