---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/es/homepage.yml
  label: Contenido
  match: "**/*"
- type: document
  path: content/spanish/contact/_index.md
  label: Contacto
  match: "**/*"
- type: document
  path: content/spanish/terms-conditions/_index.md
  label: Términos y condiciones
  match: "**/*"
- type: document
  path: content/spanish/privacy-policy/_index.md
  label: " Política de privacidad"
  match: "**/*"
- type: document
  path: i18n/es.yaml
  label: Idioma
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
